// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: addressbook.proto
#ifndef GRPC_addressbook_2eproto__INCLUDED
#define GRPC_addressbook_2eproto__INCLUDED

#include "addressbook.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace expcmake {

class AddressBook final {
 public:
  static constexpr char const* service_full_name() {
    return "expcmake.AddressBook";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetAddress(::grpc::ClientContext* context, const ::expcmake::NameQuerry& request, ::expcmake::Address* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::expcmake::Address>> AsyncGetAddress(::grpc::ClientContext* context, const ::expcmake::NameQuerry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::expcmake::Address>>(AsyncGetAddressRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::expcmake::Address>> PrepareAsyncGetAddress(::grpc::ClientContext* context, const ::expcmake::NameQuerry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::expcmake::Address>>(PrepareAsyncGetAddressRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetAddress(::grpc::ClientContext* context, const ::expcmake::NameQuerry* request, ::expcmake::Address* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetAddress(::grpc::ClientContext* context, const ::expcmake::NameQuerry* request, ::expcmake::Address* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::expcmake::Address>* AsyncGetAddressRaw(::grpc::ClientContext* context, const ::expcmake::NameQuerry& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::expcmake::Address>* PrepareAsyncGetAddressRaw(::grpc::ClientContext* context, const ::expcmake::NameQuerry& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetAddress(::grpc::ClientContext* context, const ::expcmake::NameQuerry& request, ::expcmake::Address* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::expcmake::Address>> AsyncGetAddress(::grpc::ClientContext* context, const ::expcmake::NameQuerry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::expcmake::Address>>(AsyncGetAddressRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::expcmake::Address>> PrepareAsyncGetAddress(::grpc::ClientContext* context, const ::expcmake::NameQuerry& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::expcmake::Address>>(PrepareAsyncGetAddressRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetAddress(::grpc::ClientContext* context, const ::expcmake::NameQuerry* request, ::expcmake::Address* response, std::function<void(::grpc::Status)>) override;
      void GetAddress(::grpc::ClientContext* context, const ::expcmake::NameQuerry* request, ::expcmake::Address* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::expcmake::Address>* AsyncGetAddressRaw(::grpc::ClientContext* context, const ::expcmake::NameQuerry& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::expcmake::Address>* PrepareAsyncGetAddressRaw(::grpc::ClientContext* context, const ::expcmake::NameQuerry& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetAddress_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetAddress(::grpc::ServerContext* context, const ::expcmake::NameQuerry* request, ::expcmake::Address* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetAddress : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetAddress() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetAddress() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAddress(::grpc::ServerContext* /*context*/, const ::expcmake::NameQuerry* /*request*/, ::expcmake::Address* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAddress(::grpc::ServerContext* context, ::expcmake::NameQuerry* request, ::grpc::ServerAsyncResponseWriter< ::expcmake::Address>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetAddress<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetAddress : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetAddress() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::expcmake::NameQuerry, ::expcmake::Address>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::expcmake::NameQuerry* request, ::expcmake::Address* response) { return this->GetAddress(context, request, response); }));}
    void SetMessageAllocatorFor_GetAddress(
        ::grpc::MessageAllocator< ::expcmake::NameQuerry, ::expcmake::Address>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::expcmake::NameQuerry, ::expcmake::Address>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetAddress() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAddress(::grpc::ServerContext* /*context*/, const ::expcmake::NameQuerry* /*request*/, ::expcmake::Address* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAddress(
      ::grpc::CallbackServerContext* /*context*/, const ::expcmake::NameQuerry* /*request*/, ::expcmake::Address* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetAddress<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetAddress : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetAddress() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetAddress() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAddress(::grpc::ServerContext* /*context*/, const ::expcmake::NameQuerry* /*request*/, ::expcmake::Address* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetAddress : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetAddress() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetAddress() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAddress(::grpc::ServerContext* /*context*/, const ::expcmake::NameQuerry* /*request*/, ::expcmake::Address* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAddress(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetAddress : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetAddress() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetAddress(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetAddress() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAddress(::grpc::ServerContext* /*context*/, const ::expcmake::NameQuerry* /*request*/, ::expcmake::Address* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAddress(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetAddress : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetAddress() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::expcmake::NameQuerry, ::expcmake::Address>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::expcmake::NameQuerry, ::expcmake::Address>* streamer) {
                       return this->StreamedGetAddress(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetAddress() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetAddress(::grpc::ServerContext* /*context*/, const ::expcmake::NameQuerry* /*request*/, ::expcmake::Address* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetAddress(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::expcmake::NameQuerry,::expcmake::Address>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetAddress<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetAddress<Service > StreamedService;
};

}  // namespace expcmake


#endif  // GRPC_addressbook_2eproto__INCLUDED
