// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: addressbook.proto

#include "addressbook.pb.h"
#include "addressbook.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace expcmake {

static const char* AddressBook_method_names[] = {
  "/expcmake.AddressBook/GetAddress",
};

std::unique_ptr< AddressBook::Stub> AddressBook::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AddressBook::Stub> stub(new AddressBook::Stub(channel, options));
  return stub;
}

AddressBook::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetAddress_(AddressBook_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AddressBook::Stub::GetAddress(::grpc::ClientContext* context, const ::expcmake::NameQuerry& request, ::expcmake::Address* response) {
  return ::grpc::internal::BlockingUnaryCall< ::expcmake::NameQuerry, ::expcmake::Address, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAddress_, context, request, response);
}

void AddressBook::Stub::async::GetAddress(::grpc::ClientContext* context, const ::expcmake::NameQuerry* request, ::expcmake::Address* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::expcmake::NameQuerry, ::expcmake::Address, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAddress_, context, request, response, std::move(f));
}

void AddressBook::Stub::async::GetAddress(::grpc::ClientContext* context, const ::expcmake::NameQuerry* request, ::expcmake::Address* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAddress_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::expcmake::Address>* AddressBook::Stub::PrepareAsyncGetAddressRaw(::grpc::ClientContext* context, const ::expcmake::NameQuerry& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::expcmake::Address, ::expcmake::NameQuerry, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAddress_, context, request);
}

::grpc::ClientAsyncResponseReader< ::expcmake::Address>* AddressBook::Stub::AsyncGetAddressRaw(::grpc::ClientContext* context, const ::expcmake::NameQuerry& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAddressRaw(context, request, cq);
  result->StartCall();
  return result;
}

AddressBook::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AddressBook_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AddressBook::Service, ::expcmake::NameQuerry, ::expcmake::Address, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AddressBook::Service* service,
             ::grpc::ServerContext* ctx,
             const ::expcmake::NameQuerry* req,
             ::expcmake::Address* resp) {
               return service->GetAddress(ctx, req, resp);
             }, this)));
}

AddressBook::Service::~Service() {
}

::grpc::Status AddressBook::Service::GetAddress(::grpc::ServerContext* context, const ::expcmake::NameQuerry* request, ::expcmake::Address* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace expcmake

